// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesModule.Infrastructure.Data;

#nullable disable

namespace SalesModule.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesModule.Domain.Deal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpectedCloseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("PipelineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Value", "SalesModule.Domain.Deal.Value#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Value_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Value_Currency");
                        });

                    b.HasKey("Id");

                    b.ToTable("Deals", "sales");
                });

            modelBuilder.Entity("SalesModule.Domain.DealMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DealId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("DealMovements", "sales");

                    b.HasDiscriminator<string>("MovementType").HasValue("DealMovement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SalesModule.Domain.Pipeline", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pipelines", "sales");
                });

            modelBuilder.Entity("SalesModule.Domain.Stage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PipelineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Probability")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.ToTable("Stages", "sales");
                });

            modelBuilder.Entity("SalesModule.Infrastructure.Data.Outbox.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "sales");
                });

            modelBuilder.Entity("SalesModule.Domain.DealReopen", b =>
                {
                    b.HasBaseType("SalesModule.Domain.DealMovement");

                    b.Property<string>("ReturnedToStageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DealReopen");
                });

            modelBuilder.Entity("SalesModule.Domain.StageChange", b =>
                {
                    b.HasBaseType("SalesModule.Domain.DealMovement");

                    b.Property<string>("FromStageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToStageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("StageChange");
                });

            modelBuilder.Entity("SalesModule.Domain.TerminalMovement", b =>
                {
                    b.HasBaseType("SalesModule.Domain.DealMovement");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("TerminalMovement");
                });

            modelBuilder.Entity("SalesModule.Domain.Deal", b =>
                {
                    b.OwnsMany("SalesModule.Domain.StageSnapshot", "SnapshotStages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DealId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("PipelineId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Probability")
                                .HasColumnType("numeric");

                            b1.Property<string>("StageId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("DealId");

                            b1.ToTable("StageSnapshots", "sales");

                            b1.WithOwner()
                                .HasForeignKey("DealId");
                        });

                    b.Navigation("SnapshotStages");
                });

            modelBuilder.Entity("SalesModule.Domain.DealMovement", b =>
                {
                    b.HasOne("SalesModule.Domain.Deal", null)
                        .WithMany("DealMovements")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalesModule.Domain.Stage", b =>
                {
                    b.HasOne("SalesModule.Domain.Pipeline", null)
                        .WithMany("Stages")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalesModule.Domain.Deal", b =>
                {
                    b.Navigation("DealMovements");
                });

            modelBuilder.Entity("SalesModule.Domain.Pipeline", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
